spring:
  application:
    name: zbor
  datasource:
    url: jdbc:postgresql://localhost:5432/zbor
    username: zbor_user
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
  auth:
    max-age-seconds: 3600

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false